sonata_admin:
    title: 'w'
    title_logo: 100-logo.png
    options:
        html5_validate: false
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            content:
                label:           Business
                label_catalogue: App
                icon:            '<i class="fa fa-th"></i>'
                items:
                    - app.admin.author
                    - app.admin.project
                roles: [ROLE_ADMIN, ROLE_SONATA_ADMIN]
