sonata_page:
    slugify_service: sonata.core.slugify.cocur
    multisite: host
    use_streamed_response: false

    router_auto_register:
        enabled: true
        priority: 150
    ignore_route_patterns:
        - ^(.*)admin(.*)   # ignore admin route, ie route containing 'admin'
        - ^(.*)sonata_(.*) # ignore sonata route
        - ^(.*)fos(.*)     # ignore fos route
        - ^_(.*)           # ignore symfony routes
    ignore_routes:
        - sonata_page_cache_esi
        - sonata_page_cache_ssi
        - sonata_page_js_sync_cache
        - sonata_page_js_async_cache
        - sonata_cache_esi
        - sonata_cache_ssi
        - sonata_cache_js_async
        - sonata_cache_js_sync
        - sonata_cache_apc
    ignore_uri_patterns:
        - ^/admin\/   # ignore admin route, ie route containing 'admin'
        - ^/api\/     # ignore api route, ie route containing 'api'

    default_template: default
    templates:
        default:
            path: 'Page/layout.html.twig'
            name: 'default'
            containers:
                header:
                    name: Header
                content:
                    name: Main content
                    blocks:
                        - app.block.service.text
                footer:
                    name: Footer
            matrix:
                layout: |
                    HHHHHHHH
                    CCCCCCCC
                    CCCCCCCC
                    CCCCCCCC
                    FFFFFFFF
                mapping:
                    H: header
                    C: content
                    F: footer

    direct_publication: '%kernel.debug%'

    catch_exceptions:
        not_found: [404]    # render 404 page with "not_found" key (name generated: _page_internal_error_{key})
        fatal:     [500]    # so you can use the same page for different http errors or specify specific page for each error

    class:
        page:     'App\Entity\Sonata\Page'
        snapshot: 'App\Entity\Sonata\Snapshot'
        block:    'App\Entity\Sonata\Block'
        site:     'App\Entity\Sonata\Site'
