# Sonata Admin
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# Sonata Admin User
sonata_user_admin_security:
    resource: "@SonataUserBundle/Resources/config/routing/admin_security.xml"
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting

# Sonata User
sonata_user_security:
    resource: '@FOSUserBundle/Resources/config/routing/security.xml'
    prefix: /

sonata_user_resetting:
    resource: '@FOSUserBundle/Resources/config/routing/resetting.xml'
    prefix: /resetting

# Sonata Page
sonata_page_exceptions:
    resource: '@SonataPageBundle/Resources/config/routing/exceptions.xml'
    prefix: /

sonata_page_cache:
    resource: '@SonataPageBundle/Resources/config/routing/cache.xml'
    prefix: /

#sonata_page_api:
#    resource: '@SonataPageBundle/Resources/config/routing/api.xml'
#    prefix: /

